export const data = [
  {
    id: 1,
    billValue: 116,
    url: 'https://i.postimg.cc/XNt3rV15/Evro.jpg',
    billCount: 0,
    output: 0,
  },
  {
    id: 2,
    billValue: 5000,
    url: 'https://i.postimg.cc/G2S7SmTx/5000-lice.jpg',
    billCount: 0,
    output: 0,
  },
  {
    id: 3,
    billValue: 2000,
    url: 'https://i.postimg.cc/13pd5Sby/126305-vest-2.jpg',
    billCount: 0,
    output: 0,
  },
  {
    id: 4,
    billValue: 1000,
    url: 'https://i.postimg.cc/J0fTMYqy/1000-lice.jpg',
    billCount: 0,
    output: 0,
  },
  {
    id: 5,
    billValue: 500,
    url: 'https://i.postimg.cc/ryDMydjc/500-lice.jpg',
    billCount: 0,
    output: 0,
  },
  {
    id: 6,
    billValue: 200,
    url: 'https://i.postimg.cc/FzdWtXj5/200-lice.jpg',
    billCount: 0,
    output: 0,
  },
  {
    id: 7,
    billValue: 100,
    url: 'https://i.postimg.cc/LsD0LTH7/100-lice.jpg',
    billCount: 0,
    output: 0,
  },
  {
    id: 8,
    billValue: 50,
    url: 'https://i.postimg.cc/jjtFD9rP/50-lice.jpg',
    billCount: 0,
    output: 0,
  },
  {
    id: 9,
    billValue: 20,
    url: 'https://i.postimg.cc/bJvVTtrv/20-lice.jpg',
    billCount: 0,
    output: 0,
  },
  {
    id: 10,
    billValue: 10,
    url: 'https://i.postimg.cc/pLN7HrG0/10-lice.jpg',
    billCount: 0,
    output: 0,
  },
];
